[versions]
# libraries
annotations = "24.1.0"

# plugins
gradleIntelliJPlugin = "1.16.1"
changelog = "2.2.0"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }